apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami-beta
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  valkey:
  - instance: sessions
    access: readwrite
  - instance: reops-umami-beta
    access: readwrite
  - instance: lookup
    access: read
  env:
    - name: "DATABASE_TYPE"
      value: "postgresql"
    - name: "FORCE_SSL"
      value: "1"
    - name: "DISABLE_TELEMETRY"
      value: "1"
    - name: "REMOVE_TRAILING_SLASH"
      value: "1"
    - name: "LOG_QUERY"
      value: "0"
    - name: "SKIP_DB_CHECK"
      value: "1"
    - name: "MIGRATION_ENGINE_LOCK_TIMEOUT"
      value: "60000"
    - name: "NEXT_TMP_DIR"
      value: "/tmp/next"
  accessPolicy:
    inbound:
      rules:
        - application: reops-felgen
        - application: reops-proxy
        - application: umami-proxy
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-42-38912
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: reops-umami-beta
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://umami.ansatt.nav.no"
    - "https://umami.intern.nav.no"
  resources:
    requests:
      cpu: "800m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  liveness:
    path: "/login"
    port: 3000
  readiness:
    path: "/login"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 6
    min: 2
  port: 3000
