apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami-beta
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  env:
    - name: "DATABASE_TYPE"
      value: "postgresql"
    - name: "FORCE_SSL"
      value: "1"
    - name: "DISABLE_TELEMETRY"
      value: "1"
  accessPolicy:
    inbound:
      rules:
        - application: reops-felgen
        - application: reops-proxy
        - application: umami-proxy
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-6-5120
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: reops-umami-beta
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://umami.ansatt.nav.no"
    - "https://umami.intern.nav.no"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  liveness:
    path: "/login"
    port: 3000
  readiness:
    path: "/login"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 2
    min: 1
  port: 3000
