apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: umami-dev
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  valkey:
    - instance: umami-dev
      access: readwrite
  env:
    - name: "DATABASE_TYPE"
      value: "postgresql"
    - name: "FORCE_SSL"
      value: "1"
    - name: "DISABLE_TELEMETRY"
      value: "1"
    - name: "LOG_QUERY"
      value: "0"
    - name: "SKIP_DB_CHECK"
      value: "0"
    - name: "SKIP_DB_MIGRATION"
      value: "1"
    - name: "DEBUG"
      value: "prisma:*:info"
    - name: "DATABASE_URL"
      value: "$(NAIS_DATABASE_UMAMI_DEV_UMAMI_DEV_URL)&sslmode=no-verify"
    - name: "REDIS_URL"
      value: "rediss://$(VALKEY_USERNAME_UMAMI_DEV):$(VALKEY_PASSWORD_UMAMI_DEV)@$(VALKEY_HOST_UMAMI_DEV):$(VALKEY_PORT_UMAMI_DEV)"
  accessPolicy:
    inbound:
      rules:
        - application: umami-proxy-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: umami-dev
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://umami-dev.ansatt.nav.no"
  resources:
    requests:
      cpu: "600m"
      memory: "512Mi"
  liveness:
    path: "/login"
    port: 3000
  readiness:
    path: "/login"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 2
    min: 1
  port: 3000
