apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: reops-umami-beta
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  valkey:
    - instance: sessions
      access: readwrite
    - instance: reops-umami-beta
      access: readwrite
    - instance: lookup
      access: read
  env:
    - name: "DATABASE_TYPE"
      value: "postgresql"
    - name: "FORCE_SSL"
      value: "1"
    - name: "DISABLE_TELEMETRY"
      value: "1"
    - name: "LOG_QUERY"
      value: "0"
    - name: "SKIP_DB_MIGRATION"
      value: "1"
    - name: "DEBUG"
      value: "prisma:*:info"
    - name: "PRISMA_CLI_CACHE_DIR"
      value: "/tmp/.cache"
    - name: "DATABASE_URL"
      value: "postgresql://$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_USERNAME):$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_PASSWORD)@$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_HOST):$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_PORT)/umami-one?sslmode=no-verify&sslrootcert=$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_SSLROOTCERT)&sslcert=$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_SSLCERT)&sslkey=$(NAIS_DATABASE_REOPS_UMAMI_BETA_REOPS_UMAMI_BETA_SSLKEY)"
    - name: "REDIS_URL"
      value: "rediss://$(VALKEY_USERNAME_REOPS_UMAMI_BETA):$(VALKEY_PASSWORD_REOPS_UMAMI_BETA)@$(VALKEY_HOST_REOPS_UMAMI_BETA):$(VALKEY_PORT_REOPS_UMAMI_BETA)"
  accessPolicy:
    inbound:
      rules:
        - application: reops-felgen
        - application: reops-proxy
        - application: umami-proxy
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-24-22272
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: reops-umami-beta
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://umami.ansatt.nav.no"
    - "https://umami.intern.nav.no"
  resources:
    requests:
      cpu: "800m"
      memory: "512Mi"
  liveness:
    path: "/login"
    port: 3000
  readiness:
    path: "/login"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 8
    min: 2
  port: 3000
